# -*- coding: utf-8 -*-
"""Prova - Data Science

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10tZ9gpK8Ft6uULqCP0QcInVDggeelm_q
"""

import pandas as pd
  import matplotlib.pyplot as plt

  indicadores = pd.read_csv("/content/Indicators.csv")
  indicadores

"""#1) Urban population (% of total) X Electric power consumption (kWh per capita)"""

# Indicadores: Urban population (% of total) X Electric power consumption (kWh per capita) 
# Chile x Peru

urban_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Urban population (% of total)')]
urban_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Urban population (% of total)')]
power_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]
power_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]

df_ch_pe_urban = pd.DataFrame(columns=["Chile", "Peru"])
ch= urban_ch.set_index("Year")
pe = urban_pe.set_index("Year")
df_ch_pe_urban["Chile"] = ch["Value"]
df_ch_pe_urban["Peru"] = pe["Value"]
df_ch_pe_urban.plot()

df_ch_pe_power = pd.DataFrame(columns=["Chile", "Peru"])
ch= power_ch.set_index("Year")
pe = power_pe.set_index("Year")
df_ch_pe_power["Chile"] = ch["Value"]
df_ch_pe_power["Peru"] = pe["Value"]
df_ch_pe_power.plot()

ch_only = pd.DataFrame(data={"População_Urbana_Chile": df_ch_pe_urban["Chile"], "Consumo_Chile": df_ch_pe_power["Chile"]})
pe_only = pd.DataFrame(data={"População_Urbana_Peru": df_ch_pe_urban["Peru"], "Consumo_Peru": df_ch_pe_power["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Urban population (% of total) X Electric power consumption (kWh per capita) 
# Canada x Mexico

urban_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Urban population (% of total)')]
urban_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Urban population (% of total)')]
power_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]
power_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]

df_ca_me_urban = pd.DataFrame(columns=["Canada", "Mexico"])
ca= urban_ca.set_index("Year")
me = urban_me.set_index("Year")
df_ca_me_urban["Canada"] = ca["Value"]
df_ca_me_urban["Mexico"] = me["Value"]
df_ca_me_urban.plot()

df_ca_me_power = pd.DataFrame(columns=["Canada", "Mexico"])
ca= power_ca.set_index("Year")
me = power_me.set_index("Year")
df_ca_me_power["Canada"] = ca["Value"]
df_ca_me_power["Mexico"] = me["Value"]
df_ca_me_power.plot()

ca_only = pd.DataFrame(data={"População_Urbana_Canada": df_ca_me_urban["Canada"], "Consumo_Canada": df_ca_me_power["Canada"]})
me_only = pd.DataFrame(data={"População_Urbana_Mexico": df_ca_me_urban["Mexico"], "Consumo_Mexico": df_ca_me_power["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Urban population (% of total) X Electric power consumption (kWh per capita) 
# France x Spain

urban_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Urban population (% of total)')]
urban_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Urban population (% of total)')]
power_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]
power_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]

df_fra_spa_urban = pd.DataFrame(columns=["France", "Spain"])
fra= urban_fra.set_index("Year")
spa = urban_spa.set_index("Year")
df_fra_spa_urban["France"] = fra["Value"]
df_fra_spa_urban["Spain"] = spa["Value"]
df_fra_spa_urban.plot()

df_fra_spa_power = pd.DataFrame(columns=["France", "Spain"])
fra= power_fra.set_index("Year")
spa = power_spa.set_index("Year")
df_fra_spa_power["France"] = fra["Value"]
df_fra_spa_power["Spain"] = spa["Value"]
df_fra_spa_power.plot()

fra_only = pd.DataFrame(data={"População_Urbana_França": df_fra_spa_urban["France"], "Consumo_França": df_fra_spa_power["France"]})
spa_only = pd.DataFrame(data={"População_Urbana_Espanha": df_fra_spa_urban["Spain"], "Consumo_Espanha": df_fra_spa_power["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Urban population (% of total) X Electric power consumption (kWh per capita) 
# Russian Federation x Japan

urban_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Urban population (% of total)')]
urban_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Urban population (% of total)')]
power_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]
power_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Electric power consumption (kWh per capita)')]

df_rus_jap_urban = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= urban_rus.set_index("Year")
jap = urban_jap.set_index("Year")
df_rus_jap_urban["Russian Federation"] = rus["Value"]
df_rus_jap_urban["Japan"] = jap["Value"]
df_rus_jap_urban.plot()

df_rus_jap_power = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= power_fra.set_index("Year")
jap = power_spa.set_index("Year")
df_rus_jap_power["Russian Federation"] = rus["Value"]
df_rus_jap_power["Japan"] = jap["Value"]
df_rus_jap_power.plot()

rus_only = pd.DataFrame(data={"População_Urbana_Russia": df_rus_jap_urban["Russian Federation"], "Consumo_Russia": df_rus_jap_power["Russian Federation"]})
jap_only = pd.DataFrame(data={"População_Urbana_Espanha": df_rus_jap_urban["Japan"], "Consumo_Espanha": df_rus_jap_power["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 2) Hospital beds (per 1,000 people) x Life expectancy at birth, total (years)"""

# Indicadores: Hospital beds (per 1,000 people) x Life expectancy at birth, total (years)
# Chile x Peru

beds_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
beds_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
power_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]
power_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]

df_ch_pe_beds = pd.DataFrame(columns=["Chile", "Peru"])
ch= beds_ch.set_index("Year")
pe = beds_pe.set_index("Year")
df_ch_pe_beds["Chile"] = ch["Value"]
df_ch_pe_beds["Peru"] = pe["Value"]
df_ch_pe_beds.plot()

df_ch_pe_power = pd.DataFrame(columns=["Chile", "Peru"])
ch= power_ch.set_index("Year")
pe = power_pe.set_index("Year")
df_ch_pe_power["Chile"] = ch["Value"]
df_ch_pe_power["Peru"] = pe["Value"]
df_ch_pe_power.plot()

ch_only = pd.DataFrame(data={"Camas_de_Hospital_Chile": df_ch_pe_beds["Chile"], "Expectativa_de_Vida_Chile": df_ch_pe_power["Chile"]})
pe_only = pd.DataFrame(data={"Camas_de_Hospital_Peru": df_ch_pe_beds["Peru"], "Expectativa_de_Vida_Peru": df_ch_pe_power["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Hospital beds (per 1,000 people) X Life expectancy at birth, total (years) 
# Canada x Mexico

beds_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
beds_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
power_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]
power_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]

df_ca_me_beds = pd.DataFrame(columns=["Canada", "Mexico"])
ca= beds_ca.set_index("Year")
me = beds_me.set_index("Year")
df_ca_me_beds["Canada"] = ca["Value"]
df_ca_me_beds["Mexico"] = me["Value"]
df_ca_me_beds.plot()

df_ca_me_power = pd.DataFrame(columns=["Canada", "Mexico"])
ca= power_ca.set_index("Year")
me = power_me.set_index("Year")
df_ca_me_power["Canada"] = ca["Value"]
df_ca_me_power["Mexico"] = me["Value"]
df_ca_me_power.plot()

ca_only = pd.DataFrame(data={"Camas_de_Hospital_Canada": df_ca_me_beds["Canada"], "Expectativa_de_Vida_Canada": df_ca_me_power["Canada"]})
me_only = pd.DataFrame(data={"Camas_de_Hospital_Mexico": df_ca_me_beds["Mexico"], "Expectativa_de_Vida_Mexico": df_ca_me_power["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Hospital beds (per 1,000 people) X Life expectancy at birth, total (years) 
# France x Spain

beds_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
beds_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
power_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]
power_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]

df_fra_spa_beds = pd.DataFrame(columns=["France", "Spain"])
fra= beds_fra.set_index("Year")
spa = beds_spa.set_index("Year")
df_fra_spa_beds["France"] = fra["Value"]
df_fra_spa_beds["Spain"] = spa["Value"]
df_fra_spa_beds.plot()

df_fra_spa_power = pd.DataFrame(columns=["France", "Spain"])
fra= power_fra.set_index("Year")
spa = power_spa.set_index("Year")
df_fra_spa_power["France"] = fra["Value"]
df_fra_spa_power["Spain"] = spa["Value"]
df_fra_spa_power.plot()

fra_only = pd.DataFrame(data={"Camas_de_Hospital_França": df_fra_spa_beds["France"], "Expectativa_de_Vida_França": df_fra_spa_power["France"]})
spa_only = pd.DataFrame(data={"Camas_de_Hospital_Espanha": df_fra_spa_beds["Spain"], "Expectativa_de_Vida_Espanha": df_fra_spa_power["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Hospital beds (per 1,000 people) X Life expectancy at birth, total (years) 
# Russian Federation x Japan

beds_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
beds_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Hospital beds (per 1,000 people)')]
power_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]
power_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Life expectancy at birth, total (years)')]

df_rus_jap_beds = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= beds_rus.set_index("Year")
jap = beds_jap.set_index("Year")
df_rus_jap_beds["Russian Federation"] = rus["Value"]
df_rus_jap_beds["Japan"] = jap["Value"]
df_rus_jap_beds.plot()

df_rus_jap_power = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= power_fra.set_index("Year")
jap = power_spa.set_index("Year")
df_rus_jap_power["Russian Federation"] = rus["Value"]
df_rus_jap_power["Japan"] = jap["Value"]
df_rus_jap_power.plot()

rus_only = pd.DataFrame(data={"Camas_de_Hospital_Russia": df_rus_jap_beds["Russian Federation"], "Expectativa_de_Vida_Russia": df_rus_jap_power["Russian Federation"]})
jap_only = pd.DataFrame(data={"Camas_de_Hospital_Japão": df_rus_jap_beds["Japan"], "Expectativa_de_Vida_Japão": df_rus_jap_power["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 3) 	Population in urban agglomerations of more than 1 million (% of total population)x CO2 emissions from liquid fuel consumption (% of total)"""

# Indicadores: Population in urban agglomerations of more than 1 million (% of total population) x CO2 emissions from liquid fuel consumption (% of total)
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"Aglomeração_Populacional_Chile": df_ch_pe_1["Chile"], "Expectativa_de_Vida_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"Aglomeração_Populacional_Peru": df_ch_pe_1["Peru"], "Emissão_CO2_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Population in urban agglomerations of more than 1 million (% of total population) X CO2 emissions from liquid fuel consumption (% of total) 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"Aglomeração_Populacional_Canada": df_ca_me_1["Canada"], "Emissão_CO2_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"Aglomeração_Populacional_Mexico": df_ca_me_1["Mexico"], "Emissão_CO2_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Population in urban agglomerations of more than 1 million (% of total population) X CO2 emissions from liquid fuel consumption (% of total) 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"Aglomeração_Populacional_França": df_fra_spa_1["France"], "Emissão_CO2_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"Aglomeração_Populacional_Espanha": df_fra_spa_1["Spain"], "Emissão_CO2_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Population in urban agglomerations of more than 1 million (% of total population) X CO2 emissions from liquid fuel consumption (% of total) 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Population in urban agglomerations of more than 1 million (% of total population)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='CO2 emissions from liquid fuel consumption (% of total)')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"Aglomeração_Populacional_Russia": df_rus_jap_1["Russian Federation"], "Emissão_CO2_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"Aglomeração_Populacional_Japão": df_rus_jap_1["Japan"], "Emissão_CO2_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 4) 	Birth rate, crude (per 1,000 people) x 	Death rate, crude (per 1,000 people)"""

# Indicadores: Birth rate, crude (per 1,000 people) x Death rate, crude (per 1,000 people)
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"Taxa_de_Nascimento_Chile": df_ch_pe_1["Chile"], "Taxa_de_Mortalidade_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"Taxa_de_Nascimento_Peru": df_ch_pe_1["Peru"], "Taxa_de_Mortalidade_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Death rate, crude (per 1,000 people) 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"Taxa_de_Nascimento_Canada": df_ca_me_1["Canada"], "Taxa_de_Mortalidade_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"Taxa_de_Nascimento_Mexico": df_ca_me_1["Mexico"], "Taxa_de_Mortalidade_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Death rate, crude (per 1,000 people) 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"Taxa_de_Nascimento_França": df_fra_spa_1["France"], "Taxa_de_Mortalidade_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"Taxa_de_Nascimento_Espanha": df_fra_spa_1["Spain"], "Taxa_de_Mortalidade_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Death rate, crude (per 1,000 people) 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Death rate, crude (per 1,000 people)')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"Taxa_de_Nascimento_Russia": df_rus_jap_1["Russian Federation"], "Taxa_de_Mortalidade_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"Taxa_de_Nascimento_Japão": df_rus_jap_1["Japan"], "Taxa_de_Mortalidade_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 5) 	Birth rate, crude (per 1,000 people) x 	Adolescent fertility rate (births per 1,000 women ages 15-19)"""

# Indicadores: Birth rate, crude (per 1,000 people) x Adolescent fertility rate (births per 1,000 women ages 15-19)
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"Taxa_de_Nascimento_Chile": df_ch_pe_1["Chile"], "Fertilidade_Adolescente_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"Taxa_de_Nascimento_Peru": df_ch_pe_1["Peru"], "Fertilidade_Adolescente_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Adolescent fertility rate (births per 1,000 women ages 15-19) 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"Taxa_de_Nascimento_Canada": df_ca_me_1["Canada"], "Fertilidade_Adolescente_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"Taxa_de_Nascimento_Mexico": df_ca_me_1["Mexico"], "Fertilidade_Adolescente_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Adolescent fertility rate (births per 1,000 women ages 15-19) 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"Taxa_de_Nascimento_França": df_fra_spa_1["France"], "Fertilidade_Adolescente_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"Taxa_de_Nascimento_Espanha": df_fra_spa_1["Spain"], "Fertilidade_Adolescente_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Adolescent fertility rate (births per 1,000 women ages 15-19) 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Adolescent fertility rate (births per 1,000 women ages 15-19)')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"Taxa_de_Nascimento_Russia": df_rus_jap_1["Russian Federation"], "Fertilidade_Adolescente_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"Taxa_de_Nascimento_Japão": df_rus_jap_1["Japan"], "Fertilidade_Adolescente_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 6) 	GDP per capita (current US$) x 	Mobile cellular subscriptions"""

# Indicadores: GDP per capita (current US$) x Mobile cellular subscriptions
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"PIB_per_capta_Chile": df_ch_pe_1["Chile"], "Inscrições_Smartphones_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"PIB_per_capta_Peru": df_ch_pe_1["Peru"], "Inscrições_Smartphones_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: GDP per capita (current US$) X Mobile cellular subscriptions 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"PIB_per_capta_Canada": df_ca_me_1["Canada"], "Inscrições_Smartphones_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"PIB_per_capta_Mexico": df_ca_me_1["Mexico"], "Inscrições_Smartphones_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: GDP per capita (current US$) X Mobile cellular subscriptions 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"PIB_per_capta_França": df_fra_spa_1["France"], "Inscrições_Smartphones_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"PIB_per_capta_Espanha": df_fra_spa_1["Spain"], "Inscrições_Smartphones_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: GDP per capita (current US$) X Mobile cellular subscriptions 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='GDP per capita (current US$)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Mobile cellular subscriptions')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"PIB_per_capta_Russia": df_rus_jap_1["Russian Federation"], "Inscrições_Smartphones_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"PIB_per_capta_Japão": df_rus_jap_1["Japan"], "Inscrições_Smartphones_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 7) 	Age dependency ratio, young (% of working-age population) x 	Mortality rate, infant (per 1,000 live births)"""

# Indicadores: Age dependency ratio, young (% of working-age population) x Mortality rate, infant (per 1,000 live births)
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"Trabalho_Infantil_Chile": df_ch_pe_1["Chile"], "Mortalidade_Infantil_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"Trabalho_Infantil_Peru": df_ch_pe_1["Peru"], "Mortalidade_Infantil_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Age dependency ratio, young (% of working-age population) X Mortality rate, infant (per 1,000 live births) 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"Trabalho_Infantil_Canada": df_ca_me_1["Canada"], "Mortalidade_Infantil_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"Trabalho_Infantil_Mexico": df_ca_me_1["Mexico"], "Mortalidade_Infantil_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Age dependency ratio, young (% of working-age population) X Mortality rate, infant (per 1,000 live births) 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"Trabalho_Infantil_França": df_fra_spa_1["France"], "Mortalidade_Infantil_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"Trabalho_Infantil_Espanha": df_fra_spa_1["Spain"], "Mortalidade_Infantil_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Age dependency ratio, young (% of working-age population) X Mortality rate, infant (per 1,000 live births) 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Age dependency ratio, young (% of working-age population)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Mortality rate, infant (per 1,000 live births)')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"Trabalho_Infantil_Russia": df_rus_jap_1["Russian Federation"], "Mortalidade_Infantil_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"Trabalho_Infantil_Japão": df_rus_jap_1["Japan"], "Mortalidade_Infantil_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 8) Birth rate, crude (per 1,000 people) x Population, ages 0-14 (% of total)"""

# Indicadores: Birth rate, crude (per 1,000 people) x Population, ages 0-14 (% of total)
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"Taxa_Nascimento_Chile": df_ch_pe_1["Chile"], "Pop_Até_14_Anos_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"Taxa_Nascimento_Peru": df_ch_pe_1["Peru"], "Pop_Até_14_Anos_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Population, ages 0-14 (% of total) 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"Taxa_Nascimento_Canada": df_ca_me_1["Canada"], "Pop_Até_14_Anos_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"Taxa_Nascimento_Mexico": df_ca_me_1["Mexico"], "Pop_Até_14_Anos_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Population, ages 0-14 (% of total) 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"Taxa_Nascimento_França": df_fra_spa_1["France"], "Pop_Até_14_Anos_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"Taxa_Nascimento_Espanha": df_fra_spa_1["Spain"], "Pop_Até_14_Anos_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Birth rate, crude (per 1,000 people) X Population, ages 0-14 (% of total) 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Birth rate, crude (per 1,000 people)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Population, ages 0-14 (% of total)')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"Taxa_Nascimento_Russia": df_rus_jap_1["Russian Federation"], "Pop_Até_14_Anos_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"Taxa_Nascimento_Japão": df_rus_jap_1["Japan"], "Pop_Até_14_Anos_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 9) Electricity production from oil sources (% of total) x 	Energy use (kg of oil equivalent per capita)"""

# Indicadores: Electricity production from oil sources (% of total) x Energy use (kg of oil equivalent per capita)
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"Produção_Energia_Chile": df_ch_pe_1["Chile"], "Uso_Energia_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"Produção_Energia_Peru": df_ch_pe_1["Peru"], "Uso_Energia_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Electricity production from oil sources (% of total) X Energy use (kg of oil equivalent per capita) 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"Produção_Energia_Canada": df_ca_me_1["Canada"], "Uso_Energia_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"Produção_Energia_Mexico": df_ca_me_1["Mexico"], "Uso_Energia_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Electricity production from oil sources (% of total) X Energy use (kg of oil equivalent per capita) 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"Produção_Energia_França": df_fra_spa_1["France"], "Uso_Energia_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"Produção_Energia_Espanha": df_fra_spa_1["Spain"], "Uso_Energia_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Electricity production from oil sources (% of total) X Energy use (kg of oil equivalent per capita) 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Electricity production from oil sources (% of total)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Energy use (kg of oil equivalent per capita)')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"Produção_Energia_Russia": df_rus_jap_1["Russian Federation"], "Uso_Energia_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"Produção_Energia_Japão": df_rus_jap_1["Japan"], "Uso_Energia_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()

"""# 10) Rural population (% of total population) x CO2 emissions from transport (% of total fuel combustion)"""

# Indicadores: Rural population (% of total population) x CO2 emissions from transport (% of total fuel combustion)
# Chile x Peru

indicator_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator2_ch = indicadores[(indicadores['CountryName'] == "Chile") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]
indicator2_pe = indicadores[(indicadores['CountryName'] == "Peru") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]

df_ch_pe_1 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator_ch.set_index("Year")
pe = indicator_pe.set_index("Year")
df_ch_pe_1["Chile"] = ch["Value"]
df_ch_pe_1["Peru"] = pe["Value"]
df_ch_pe_1.plot()

df_ch_pe_2 = pd.DataFrame(columns=["Chile", "Peru"])
ch= indicator2_ch.set_index("Year")
pe = indicator2_pe.set_index("Year")
df_ch_pe_2["Chile"] = ch["Value"]
df_ch_pe_2["Peru"] = pe["Value"]
df_ch_pe_2.plot()

ch_only = pd.DataFrame(data={"População_Rural_Chile": df_ch_pe_1["Chile"], "Emissão_CO2_Chile": df_ch_pe_2["Chile"]})
pe_only = pd.DataFrame(data={"População_Rural_Peru": df_ch_pe_1["Peru"], "Emissão_CO2_Peru": df_ch_pe_2["Peru"]})
ch_pe_merge = pd.merge(ch_only, pe_only, left_index=True, right_index=True)
ch_pe_merge.plot()

# Indicadores: Rural population (% of total population) X CO2 emissions from transport (% of total fuel combustion) 
# Canada x Mexico

indicator_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator2_ca = indicadores[(indicadores['CountryName'] == "Canada") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]
indicator2_me = indicadores[(indicadores['CountryName'] == "Mexico") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]

df_ca_me_1 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator_ca.set_index("Year")
me = indicator_me.set_index("Year")
df_ca_me_1["Canada"] = ca["Value"]
df_ca_me_1["Mexico"] = me["Value"]
df_ca_me_1.plot()

df_ca_me_2 = pd.DataFrame(columns=["Canada", "Mexico"])
ca= indicator2_ca.set_index("Year")
me = indicator2_me.set_index("Year")
df_ca_me_2["Canada"] = ca["Value"]
df_ca_me_2["Mexico"] = me["Value"]
df_ca_me_2.plot()

ca_only = pd.DataFrame(data={"População_Rural_Canada": df_ca_me_1["Canada"], "Emissão_CO2_Canada": df_ca_me_2["Canada"]})
me_only = pd.DataFrame(data={"População_Rural_Mexico": df_ca_me_1["Mexico"], "Emissão_CO2_Mexico": df_ca_me_2["Mexico"]})
ca_me_merge = pd.merge(ca_only, me_only, left_index=True, right_index=True)
ca_me_merge.plot()

# Indicadores: Rural population (% of total population) X CO2 emissions from transport (% of total fuel combustion) 
# France x Spain

indicator_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator2_fra = indicadores[(indicadores['CountryName'] == "France") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]
indicator2_spa = indicadores[(indicadores['CountryName'] == "Spain") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]

df_fra_spa_1 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator_fra.set_index("Year")
spa = indicator_spa.set_index("Year")
df_fra_spa_1["France"] = fra["Value"]
df_fra_spa_1["Spain"] = spa["Value"]
df_fra_spa_1.plot()

df_fra_spa_2 = pd.DataFrame(columns=["France", "Spain"])
fra= indicator2_fra.set_index("Year")
spa = indicator2_spa.set_index("Year")
df_fra_spa_2["France"] = fra["Value"]
df_fra_spa_2["Spain"] = spa["Value"]
df_fra_spa_2.plot()

fra_only = pd.DataFrame(data={"População_Rural_França": df_fra_spa_1["France"], "Emissão_CO2_França": df_fra_spa_2["France"]})
spa_only = pd.DataFrame(data={"População_Rural_Espanha": df_fra_spa_1["Spain"], "Emissão_CO2_Espanha": df_fra_spa_2["Spain"]})
fra_spa_merge = pd.merge(fra_only, spa_only, left_index=True, right_index=True)
fra_spa_merge.plot()

# Indicadores: Rural population (% of total population) X CO2 emissions from transport (% of total fuel combustion) 
# Russian Federation x Japan

indicator_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='Rural population (% of total population)')]
indicator2_rus = indicadores[(indicadores['CountryName'] == "Russian Federation") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]
indicator2_jap = indicadores[(indicadores['CountryName'] == "Japan") & (indicadores['IndicatorName']=='CO2 emissions from transport (% of total fuel combustion)')]

df_rus_jap_1 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator_rus.set_index("Year")
jap = indicator_jap.set_index("Year")
df_rus_jap_1["Russian Federation"] = rus["Value"]
df_rus_jap_1["Japan"] = jap["Value"]
df_rus_jap_1.plot()

df_rus_jap_2 = pd.DataFrame(columns=["Russian Federation", "Japan"])
rus= indicator2_fra.set_index("Year")
jap = indicator2_spa.set_index("Year")
df_rus_jap_2["Russian Federation"] = rus["Value"]
df_rus_jap_2["Japan"] = jap["Value"]
df_rus_jap_2.plot()

rus_only = pd.DataFrame(data={"População_Rural_Russia": df_rus_jap_1["Russian Federation"], "Emissão_CO2_Russia": df_rus_jap_2["Russian Federation"]})
jap_only = pd.DataFrame(data={"População_Rural_Japão": df_rus_jap_1["Japan"], "Emissão_CO2_Japão": df_rus_jap_2["Japan"]})
rus_jap_merge = pd.merge(rus_only, jap_only, left_index=True, right_index=True)
rus_jap_merge.plot()